server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
            
        - id: authentication-service-docs
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/authentication-service/api-docs/**

        - id: test
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/test
          filters:
            - Authentication

        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/api/v1/profiles/**,/api/v1/follows/**
          filters:
            - Authentication
            
        - id: profile-service-docs
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/profile-service/api-docs/**
            
        - id: tweet-service
          uri: lb://TWEET-SERVICE
          predicates:
            - Path=/api/v1/tweets/**,/api/v1/likes/**,/api/v1/retweets/**,/api/v1/replies/**
          filters:
            - Authentication
            
        - id: tweet-service-docs
          uri: lb://TWEET-SERVICE
          predicates:
            - Path=/tweet-service/api-docs/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: http://localhost:8080/v3/api-docs
    urls:
      - name: tweet-service
        url: /tweet-service/api-docs

      - name: profile-service
        url: /profile-service/api-docs

      - name: authentication-service
        url: /authentication-service/api-docs

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace

services:
  auth:
    name: authentication-service
